title: TanMeiZi's Homepage
page-top-title: TanMeiZi
top-section-bg-text: Be what you wanna be
home-subtitle: TanMeiZi&ensp;|&ensp;谭美姿
copyright-text: "&copy; TanMeiZi 2023-2025. All Rights Reserved."
